tasks = {
    'rating': {
        '0': ('What star rating user {user_id} will give item {item_id}.', '{rating}', 'accuracy'),
        '1': ('What star rating user {user_id} will give item {item_title}.', '{rating}', 'accuracy'),
        '2': ('What star rating user {user_desc} will give item {item_id}.', '{rating}', 'accuracy'),
        '3': ('What star rating user {user_desc} will give item {item_title}.', '{rating}', 'accuracy'),
        '4': ('How will user {user_id} rate the item {item_id}.', '{rating}', 'accuracy'),
        '5': ('How will user {user_id} rate the item {item_title}.', '{rating}', 'accuracy'),
        '6': ('How will user {user_desc} rate the item {item_id}.', '{rating}', 'accuracy'),
        '7': ('How will user {user_desc} rate the item {item_title}.', '{rating}', 'accuracy'),
        '8': ('Predict user {user_id} preference on item {item_id} {item_title}', '{rating}', 'accuracy'),
        '9': ('Predict user {user_desc} preference on item {item_id} {item_title}', '{rating}', 'accuracy'),
        '10': ('Predict user {user_id} {user_desc} preference on item {item_id} {item_title}', '{rating}', 'accuracy'),
        '11': ('Does the user {user_id} give a {rating} rating to the item {item_id}.  (yes,  no)', 'NA', 'accuracy'),
        '12': ('Does the user {user_id} give a {rating} rating to the item {item_title}.  (yes,  no)', 'NA', 'accuracy'),
        '13': ('Does the user {user_desc} give a {rating} rating to the item {item_id}.  (yes,  no)', 'NA', 'accuracy'),
        '14': ('Does the user {user_desc} give a {rating} rating to the item {item_title}.  (yes,  no)', 'NA', 'accuracy'),
        '15': ('Will the user {user_id} like item {item_id}, (like means 4/5 rating,  dislike means 1/2/3 rating)', 'NA', 'accuracy'),
        '16': ('Will the user {user_id} like item {item_title}, (like means 4/5 rating,  dislike means 1/2/3 rating)', 'NA', 'accuracy'),
        '17': ('Will the user {user_desc} like item {item_id}, (like means 4/5 rating,  dislike means 1/2/3 rating)', 'NA', 'accuracy'),
        '18': ('Will the user {user_desc} like item {item_title}, (like means 4/5 rating,  dislike means 1/2/3 rating)', 'NA', 'accuracy')
    },

    'sequential': {
        '0': ('Given the visiting history of the user {user_id} {item_id_list}, predict the next possible visit of the user. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '1': ('Given the visiting history of the user {user_desc} {item_id_list}, predict the next possible visit of the user. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '2': ('Given the visiting history of the user {user_id} {item_title_list}, predict the next possible visit of the user. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '3': ('Given the visiting history of the user {user_desc} {item_title_list}, predict the next possible visit of the user. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '4': ('Here is the visit history of the user {user_id}, {item_id_list}, recommend next item to the user. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '5': ('Here is the visit history of the user {user_id}, {item_title_list}, recommend next item to the user. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '6': ('Here is the visit history of the user {user_desc}, {item_id_list}, recommend next item to the user. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '7': ('Here is the visit history of the user {user_desc}, {item_title_list}, recommend next item to the user. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '8': ('Given the past visit history {item_id_list} of user {user_id}, what item he may go for next. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '9': ('Given the past visit history {item_id_list} of user {user_desc}, what item he may go for next. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '10': ('Given the past visit history {item_title_list} of user {user_id}, what item he may go for next.', '{target_item_id}', 'HR, NDCG, MRR'),
        '11': ('Given the past visit history {item_title_list} of user {user_desc}, what item he may go for next. ', '{target_item_id}', 'HR, NDCG, MRR'),
        '12': ('Here is the visit history of user {user_id}: {item_id_list}, Select the next possible business likely to be visited by the user from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '13': ('Here is the visit history of user {user_desc}: {item_id_list}, Select the next possible business likely to be visited by the user from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '14': ('Here is the visit history of user {user_id}: {item_title_list}, Select the next possible business likely to be visited by the user from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '15': ('Here is the visit history of user {user_desc}: {item_title_list}, Select the next possible business likely to be visited by the user from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '16': ('Based on the visit history of user {user_id}: {item_id_list}, Choose the next possible visited business from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '17': ('Based on the visit history of user {user_desc}: {item_id_list}, Choose the next possible visited business from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '18': ('Based on the visit history of user {user_id}: {item_title_list}, Choose the next possible visited business from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '19': ('Based on the visit history of user {user_desc}: {item_title_list}, Choose the next possible visited business from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '20': ('I find the visit history list of {user_id}: {item_id_list}, I wonder which is the next item to recommend to the user. Try to select one from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '21': ('I find the visit history list of {user_desc}: {item_id_list}, I wonder which is the next item to recommend to the user. Try to select one from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '22': ('I find the visit history list of {user_id}: {item_title_list}, I wonder which is the next item to recommend to the user. Try to select one from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '23': ('I find the visit history list of {user_desc}: {item_title_list}, I wonder which is the next item to recommend to the user. Try to select one from the following candidates: {candiate_item_id_list}', '{target_item_id}', 'HR, NDCG, MRR'),
        '24': ('User {user_id} has the following visit history: {item_id_list}, Does the user likely to visit {target_item_id} next ?? (yes/no)', 'NA', 'accuracy'),
        '25': ('User {user_desc} has the following visit history: {item_id_list}, Does the user likely to visit {target_item_id} next ?? (yes/no)', 'NA', 'accuracy'),
        '26': ('User {user_id} has the following visit history: {item_title_list}, Does the user likely to visit {target_item_id} next ?? (yes/no)', 'NA', 'accuracy'),
        '27': ('User {user_desc} has the following visit history: {item_title_list}, Does the user likely to visit {target_item_id} next ?? (yes/no)', 'NA', 'accuracy'),
        '28': ('User {user_id} has the following visit history: {item_id_list}, Does the user likely to visit {target_item_id} next ?? (yes/no)', 'NA', 'accuracy'),
        '29': ('User {user_desc} has the following visit history: {item_title_list}, Does the user likely to visit {target_item_id} next ?? (yes/no)', 'NA', 'accuracy')
    },

    'explanation': {
        '0': ('Generate an explanation for user {user_id} about this business: {item_id}', "{explanation}", "BLUE, ROUGE"),
        '1': ('Generate an explanation for user {user_desc} about this business: {item_id}', "{explanation}", "BLUE, ROUGE"),
        '2': ('Generate an explanation for user {user_id} about this business: {item_title}', "{explanation}", "BLUE, ROUGE"),
        '3': ('Generate an explanation for user {user_desc} about this business: {item_title}', "{explanation}", "BLUE, ROUGE"),
        '4': ('Help user {user_id} generate a {rating} - star explanation about this business: {item_id}', "{explanation}", "BLUE, ROUGE"),
        '5': ('Help user {user_desc} generate a {rating} - star explanation about this business: {item_id}', "{explanation}", "BLUE, ROUGE"),
        '6': ('Help user {user_id} generate a {rating} - star explanation about this business: {item_title}', "{explanation}", "BLUE, ROUGE"),
        '7': ('Help user {user_desc} generate a {rating} - star explanation about this business: {item_title}', "{explanation}", "BLUE, ROUGE"),
        '8': ('Predict the star rating, then use {feature} as feature word to generate user {user_id} visit explanation for item {item_id}', "{rating}, {explanation}", "BLUE, ROUGE"),
        '9': ('Predict the star rating, then use {feature} as feature word to generate user {user_desc} visit explanation for item {item_id}', "{rating}, {explanation}", "BLUE, ROUGE"),
        '10': ('Predict the star rating, then use {feature} as feature word to generate user {user_id} visit explanation for item {item_title}', "{rating}, {explanation}", "BLUE, ROUGE"),
        '11': ('Predict the star rating, then use {feature} as feature word to generate user {user_desc} visit explanation for item {item_title}', "{rating}, {explanation}", "BLUE, ROUGE"),
        '12': ('What score will user {user_id} rate item {item_id}? Then give an explanation for the rating score. (1 being lowest and 5 being highest)', "{rating}, {explanation}", "BLUE, ROUGE"),
        '13': ('What score will user {user_desc} rate item {item_id}? Then give an explanation for the rating score. (1 being lowest and 5 being highest)', "{rating}, {explanation}", "BLUE, ROUGE"),
        '14': ('What score will user {user_id} rate item {item_title}? Then give an explanation for the rating score. (1 being lowest and 5 being highest)', "{rating}, {explanation}", "BLUE, ROUGE"),
        '15': ('What score will user {user_desc} rate item {item_title}? Then give an explanation for the rating score. (1 being lowest and 5 being highest)', "{rating}, {explanation}", "BLUE, ROUGE"),
        '16': ('Given the word {feature}, can you help generate an explanation for {user_id} about the business: \n {item_id}', "{explanation}", "BLUE, ROUGE"),
        '17': ('Given the word {feature}, can you help generate an explanation for {user_desc} about the business: \n {item_id}', "{explanation}", "BLUE, ROUGE"),
        '18': ('Given the word {feature}, can you help generate an explanation for {user_id} about the business: \n {item_title}', "{explanation}", "BLUE, ROUGE"),
        '19': ('Given the word {feature}, can you help generate an explanation for {user_desc} about the business: \n {item_title}', "{explanation}", "BLUE, ROUGE"),
        '20': ('Using the word {feature}, write a {rating} - star explanation for user {user_id} about item {item_id}', "{explanation}", "BLUE, ROUGE"),
        '21': ('Using the word {feature}, write a {rating} - star explanation for user {user_desc} about item {item_id}', "{explanation}", "BLUE, ROUGE"),
        '22': ('Using the word {feature}, write a {rating} - star explanation for user {user_id} about item {item_title}', "{explanation}", "BLUE, ROUGE"),
        '23': ('Using the word {feature}, write a {rating} - star explanation for user {user_desc} about item {item_title}', "{explanation}", "BLUE, ROUGE"),
        '24': ('According to the feature word {feature}, generate a {rating} - star explanation for {user_id} about item {item_id}', "{explanation}", "BLUE, ROUGE"),
        '25': ('According to the feature word {feature}, generate a {rating} - star explanation for {user_desc} about item {item_id}', "{explanation}", "BLUE, ROUGE"),
        '26': ('According to the feature word {feature}, generate a {rating} - star explanation for {user_id} about item {item_title}', "{explanation}", "BLUE, ROUGE"),
        '27': ('According to the feature word {feature}, generate a {rating} - star explanation for {user_desc} about item {item_title}', "{explanation}", "BLUE, ROUGE")
    },

    'review': {
        '0': ('Predict the associated rating score of the review written by user {user_id} (1 being lowest and 5 being highest): {review_body}', "{rating}", "accuracy"),
        '1': ('Predict the associated rating score of the review written by user {user_desc} (1 being lowest and 5 being highest): {review_body}', "{rating}", "accuracy"),
        '2': ('Given the following review written by user {user_id}: {review_body} Can you predict the associated star rating (1 being lowest and 5 being highest)?', "{rating}", "accuracy"),
        '3': ('Given the following review written by user {user_desc}: {review_body} Can you predict the associated star rating (1 being lowest and 5 being highest)?', "{rating}", "accuracy"),
        '4': ('According to the following review written by {user_id}: {review_body} Predict the associated star rating (1 being lowest and 5 being highest)', "{rating}", "accuracy"),
        '5': ('According to the following review written by {user_desc}: {review_body} Predict the associated star rating (1 being lowest and 5 being highest)', "{rating}", "accuracy")
    },

    'traditional': {
        '0': ('Will user {user_id} likely to interact with item {candidate_item_id}? (yes/no)', "NA", "accuracy"),
        '1': ('Will user {user_desc} likely to interact with item {candidate_item_id}? (yes/no)', "NA", "accuracy"),
        '2': ('Will user {user_id} likely to interact with item {candidate_item_title}? (yes/no)', "NA", "accuracy"),
        '3': ('Will user {user_desc} likely to interact with item {candidate_item_title}? (yes/no)', "NA", "accuracy"),
        '4': ('Shall we recommend item {candidate_item_id} to {user_id}? (yes/no)', "NA", "accuracy"),
        '5': ('Shall we recommend item {candidate_item_title} to {user_id}? (yes/no)', "NA", "accuracy"),
        '6': ('Shall we recommend item {candidate_item_id} to {user_desc}? (yes/no)', "NA", "accuracy"),
        '7': ('Shall we recommend item {candidate_item_title} to {user_desc}? (yes/no)', "NA", "accuracy"),
        '8': ('For {user_id}, do you think it is good to recommend {candidate_item_id}? (yes/no)', "NA", "accuracy"),
        '9': ('For {user_desc}, do you think it is good to recommend {candidate_item_id}? (yes/no)', "NA", "accuracy"),
        '10': ('For {user_id}, do you think it is good to recommend {candidate_item_title}? (yes/no)', "NA", "accuracy"),
        '11': ('For {user_desc}, do you think it is good to recommend {candidate_item_title}? (yes/no)', "NA", "accuracy"),
        '12': ('I would like to recommend some items for user {user_id}. Is the following item a good choice? {candidate_item_id} (yes/no)', "NA", "accuracy"),
        '13': ('I would like to recommend some items for user {user_desc}. Is the following item a good choice? {candidate_item_id} (yes/no)', "NA", "accuracy"),
        '14': ('I would like to recommend some items for user {user_id}. Is the following item a good choice? {candidate_item_title} (yes/no)', "NA", "accuracy"),
        '15': ('I would like to recommend some items for user {user_desc}. Is the following item a good choice? {candidate_item_title} (yes/no)', "NA", "accuracy"),
        '16': ('Which item of the following to recommend for {user_id}? {candiate_item_id_list}', "{target_item_id}", "HR, NDCG, MRR"),
        '17': ('Which item of the following to recommend for {user_desc}? {candiate_item_id_list}', "{target_item_id}", "HR, NDCG, MRR"),
        '18': ('Choose the best item from the candidates to recommend for {user_id}? {candiate_item_id_list}', "{target_item_id}", "HR, NDCG, MRR"),
        '19': ('Choose the best item from the candidates to recommend for {user_desc}? {candiate_item_id_list}', "{target_item_id}", "HR, NDCG, MRR"),
        '20': ('Pick the most suitable item from the following list and recommend to user {user_id}: {candiate_item_id_list}', "{target_item_id}", "HR, NDCG, MRR"),
        '21': ('Pick the most suitable item from the following list and recommend to user {user_desc}: {candiate_item_id_list}', "{target_item_id}", "HR, NDCG, MRR"),
    }
}